dist: trusty
sudo: false

language: scala
scala:
  - 2.12.2

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2

addons:
  postgresql: "9.6"

matrix:
  include:
    - env: SCRIPT=ci/bot-assembly.sh
    - env: SCRIPT=ci/core-testing.sh

script:
  - sh $SCRIPT
