language: scala
scala:
  - 2.12.2

jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - cp core/src/test/resources/application.conf.example core/src/test/resources/application.conf
  - psql -c 'create database pepeground_test;' -U postgres

script:
  - sbt core/test
