apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pepeground-bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pepeground-bot
    spec:
      containers:
        - image: pepeground/pepeground-bot
          name: pepeground-bot
          command:
            - '/usr/bin/java'
            - '-jar'
            - '-server'
            - '-Dconfig.file=/usr/local/etc/application.conf'
            - '/bot.jar'
          volumeMounts:
            - name: pepeground-conf
              mountPath: /usr/local/etc
      volumes:
        - name: pepeground-conf
          configMap:
            name: pepeground-conf
